

title: Di Wu # your name (or website title) here

logo: "images/professional_photo_2.JPG" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>

  MS in Business Analytics Candidate (STEM)

  Consultant at Simon Vision Consulting

  Data-driven Decision Making

  NLP | Pricing | Data Analyst | Machine Learning

  <br><br>

  <a href="https://www.linkedin.com/in/diwuethan/">View My LinkedIn Profile</a> 
  
  <a href="https://github.com/diwu437/diwu-github.io/">View My GitHub Profile</a>

  

theme: jekyll-theme-minimal

google_analytics: UA-158802514-1 # your Google Analytics tracking ID here
