title: DiWu # your name (or website title) here
logo: "Diwu photo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  MS in Business Analytics Candidate (STEM)
  Consultant at Simon Vision Consulting
  Data-driven Decision Making
  Consulting | Pricing | Data Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/diwuethan/">View My LinkedIn Profile</a> 
  <br>
theme: jekyll-theme-minimal
